# Sensor resolution
SENSOR_RESOLUTION = (512, 512)
# GroundingDINO
GROUNDINGDINO_ORIGINAL_SIZE = (800, 800)
GROUNDINGDINO_NEW_SIZE = SENSOR_RESOLUTION

SCENE_DATA_PATH = "/data/tct/habitat/data"
EVAL_DATA_PATH = "/data/tct/habitat/eval_data"
EXPERIMENT_DIR = "/data/tct/ActivePerception/exp"
TEMP_DIR = "/data/tct/ActivePerception/tmp"
MESH_TEMP_DIR = "/data/tct/ActivePerception/tmp/mesh"

REPLICACAD_TRAINING_SCENES = [
    'v3_sc3_staging_18.scene_instance.json', 
    'v3_sc0_staging_13.scene_instance.json', 
    'v3_sc1_staging_00.scene_instance.json', 
    'v3_sc0_staging_18.scene_instance.json', 
    'v3_sc3_staging_10.scene_instance.json', 
    'v3_sc1_staging_16.scene_instance.json', 
    'v3_sc1_staging_04.scene_instance.json', 
    'v3_sc3_staging_20.scene_instance.json', 
    'v3_sc0_staging_09.scene_instance.json', 
    'v3_sc2_staging_09.scene_instance.json'
    ]

HM3D_TRAINING_SCENES = [
    '00055-HxmXPBbFCkH',
    '00057-1UnKg1rAb8A',
    '00207-FRQ75PjD278',
    '00234-nACV8wLu1u5',
    '00307-vDfkYo5VqEQ',
    '00440-wPLokgvCnuk',
    '00466-xAHnY3QzFUN',
    '00537-oahi4u45xMf',
    '00680-YmWinf3mhb5',
    '00733-GtM3JtRvvvR',
]

# NOTE: Mapping from ReplicaCAD categories to DETR/COCO categories
# Multiple ReplicaCAD categories can map to the same DETR category
ReplicaCAD_to_DETR = {
    # Direct matches
    "backpack": "backpack",
    "bed": "bed",
    "bench": "bench",
    "book": "book",
    "bowl": "bowl",
    "chair": "chair",
    "clock": "clock",
    "cup": "cup",
    "handbag": "handbag",
    "laptop": "laptop",
    "microwave": "microwave",
    "refrigerator": "refrigerator",
    "sink": "sink",
    "toilet": "toilet",
    "toothbrush": "toothbrush",
    "umbrella": "umbrella",
    "vase": "vase",
    
    # Semantic matches (similar concepts)
    "bike": "bicycle",
    "computer_keyboard": "keyboard",
    "hair_dryer": "hair drier",
    "indoor_plant": "potted plant",
    "phone": "cell phone",
    "remote_control": "remote",
    "sofa": "couch",
    "table": "dining table",
    "desk": "dining table",  # Both are table surfaces
    "tv_screen": "tv",
    
    # Exercise/sports related
    "exercise_ball": "sports ball",
    
    # Note: The following ReplicaCAD categories have no clear DETR/COCO equivalents:
    # base_cabinet, basket, bathtub, blanket, blinds, cabinet, candle, cloth, 
    # clothing, curtain, desktop_computer, door, knife_block, pan, panel, 
    # paper_towel, picture, pillow, plant_stand, plate, shelf, shoe, stair, 
    # switch, tablet, window
}

replica_cad_detect_categories = list(ReplicaCAD_to_DETR.keys())

hm3d_test = {
    "tv": "tv",
    "laptop": "laptop",
    "toilet": "toilet",
    "bed": "bed",
    "couch": "couch",
    "dining table": "dining table",
    "sink": "sink",
    "refrigerator": "refrigerator",
    "microwave": "microwave",
    "oven": "oven",
    "clock": "clock",
    "vase": "vase",
    "umbrella": "umbrella",
    "bicycle": "bicycle",
    "car": "car",
    "motorcycle": "motorcycle",
    "bench": "bench",
    "keyboard": "keyboard",
    "plant": "potted plant",
    "coffee mug": "cup",
    "wine bottle": "bottle",
    "flower vase": "vase",
    "fruit bowl": "bowl",
    "dining bench": "bench"
}

# hm3d_test = {
#     "tv": "tv",
#     "laptop": "laptop",
#     "toilet": "toilet",
#     "bed": "bed",
#     "chair": "chair",
#     "couch": "couch",
#     "dining table": "dining table",
#     "sink": "sink",
#     "refrigerator": "refrigerator",
#     "microwave": "microwave",
#     "oven": "oven",
#     "clock": "clock",
#     "vase": "vase",
#     "umbrella": "umbrella",
#     "bicycle": "bicycle",
#     "car": "car",
#     "motorcycle": "motorcycle",
#     "bench": "bench",
#     "keyboard": "keyboard",
#     "plant": "potted plant",
#     "coffee mug": "cup",
#     "wine bottle": "bottle",
#     "flower vase": "vase",
#     "fruit bowl": "bowl",
#     "dining chair": "chair",
#     "office chair": "chair",
#     "swivel chair": "chair",
#     "armchair": "chair",
#     "dining bench": "bench"
# }

hm3d_to_yolo11 = {
    "tv": "tv",
    "laptop": "laptop",
    "toilet": "toilet",
    "bed": "bed",
    "chair": "chair",
    "couch": "couch",
    "dining table": "dining table",
    "sink": "sink",
    "refrigerator": "refrigerator",
    "microwave": "microwave",
    "oven": "oven",
    "toaster": "toaster",
    "book": "book",
    "clock": "clock",
    "vase": "vase",
    "teddy bear": "teddy bear",
    "umbrella": "umbrella",
    "handbag": "handbag",
    "backpack": "backpack",
    "skateboard": "skateboard",
    "bottle": "bottle",
    "cup": "cup",
    "bowl": "bowl",
    "knife": "knife",
    "person": "person",
    "bicycle": "bicycle",
    "car": "car",
    "motorcycle": "motorcycle",
    "bench": "bench",
    "dog": "dog",
    "mouse": "mouse",
    "keyboard": "keyboard",
    "plant": "potted plant",
    "coffee mug": "cup",
    "wine bottle": "bottle",
    "flower vase": "vase",
    "fruit bowl": "bowl",
    "dining chair": "chair",
    "office chair": "chair",
    "swivel chair": "chair",
    "armchair": "chair",
    "sofa set": "couch",
    "dining bench": "bench"
}

replica_cad_grounding_categories = [
    "backpack", 
    "base_cabinet", 
    "basket", 
    "bathtub", 
    "bed", 
    "bench", 
    "bike", 
    "blanket", 
    "blinds", 
    "book", 
    "bowl", 
    "cabinet", 
    "candle", 
    "chair",
    "clock", 
    "cloth", 
    "clothing", 
    "computer_keyboard", 
    "cup",
    "curtain", 
    "desk", 
    "desktop_computer",
    "door", 
    "exercise_ball", 
    "handbag", 
    "hair_dryer", 
    "indoor_plant",
    "knife_block", 
    "laptop", 
    "microwave", 
    "pan", 
    "panel", 
    "paper_towel", 
    "phone", 
    "picture", 
    "pillow", 
    "plant_stand", 
    "plate", 
    "refrigerator", 
    "remote_control", 
    "shelf",
    "shoe", 
    "sink", 
    "sofa", 
    "stair", 
    "switch", 
    "table",
    "tablet", 
    "toilet", 
    "toothbrush", 
    "tv_screen", 
    "umbrella", 
    "vase", 
    "window",
]

replica_cad_cat = [
    "backpack", 
    "base_cabinet", 
    "basket", 
    "bathtub", 
    "bed", 
    "bench", 
    "bike", 
    "bin",
    "blanket", 
    "blinds", 
    "book", 
    "bottle", 
    "box", 
    "bowl", 
    "camera", 
    "cabinet", 
    "candle", 
    "chair",
    "chopping_board", 
    "clock", 
    "cloth", 
    "clothing", 
    "comforter", 
    "computer_keyboard", 
    "cup",
    "curtain", 
    "cooktop", 
    "countertop", 
    "desk", 
    "desktop_computer",
    "door", 
    "exercise_ball", 
    "faucet", 
    "handbag", 
    "hair_dryer", 
    "indoor_plant",
    "knife_block", 
    "lamp", 
    "laptop", 
    "mat", 
    "microwave", 
    "monitor",
    "mouse", 
    "nightstand", 
    "pan", 
    "panel", 
    "paper_towel", 
    "phone", 
    "picture", 
    "pillar", 
    "pillow", 
    "pipe",
    "plant_stand", 
    "plate", 
    "pot", 
    "rack", 
    "refrigerator", 
    "remote_control", 
    "scarf", 
    "sculpture", 
    "shelf",
    "shoe", 
    "shower_stall", 
    "sink", 
    "sofa", 
    "stair", 
    "stool", 
    "switch", 
    "table",
    "tablet", 
    "tissue_paper", 
    "toilet", 
    "toothbrush", 
    "towel", 
    "tv_screen", 
    "tv_stand",
    "umbrella", 
    "utensil_holder", 
    "vase", 
    "vent", 
    "wall_cabinet", 
    "wall_plug", 
    "wardrobe", 
    "window",
    "rug", 
    "bag"
]

yolo11_to_hm3d = {
    "bicycle": ["bicycle"],
    "car": ["car"],
    "motorcycle": ["motorcycle"],        
    "chair": ["chair", "dining chair", "office chair", "swivel chair", "armchair"],
    "couch": ["couch", "sofa set"],
    "bed": ["bed"],
    "dining table": ["dining table"],      
    "tv": ["tv"],
    "laptop": ["laptop"],
    "microwave": ["microwave"],
    "oven": ["oven"],
    "toaster": ["toaster"],
    "refrigerator": ["refrigerator"],       
    "bottle": ["bottle", "wine bottle"],
    "cup": ["cup", "coffee mug"],
    "bowl": ["bowl", "fruit bowl"],
    "vase": ["vase", "flower vase"],       
    "book": ["book"],
    "clock": ["clock"],
    "umbrella": ["umbrella"],
    "handbag": ["handbag"],
    "backpack": ["backpack"],
    "skateboard": ["skateboard"], 
    "knife": ["knife"],
    "sink": ["sink"],
    "toilet": ["toilet"],
    "keyboard": ["keyboard"],
    "mouse": ["mouse"],
    "dog": ["dog"],
    "teddy bear": ["teddy bear"],
    "potted plant": ["plant"],
    "bench": ["bench", "dining bench"]
}